lumberyard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.indexView,
        name='index'
    ),
    url(r'^login/$',
        'django.contrib.auth.views.login',
        name='login',
        kwargs={'template_name':'lumberyard/login.html'}
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        name='logout',
        kwargs={'next_page': '/'}
    ),
    url(
        r'^jobSearch/$',
        views.ajaxjobsearch,
        name='jobSearch'
    ),
    url(
        r'^jobDetail/(?P<job_id>\d+)/$',
        views.JobDetailView,
        name='jobDetail'
    ),
    url(
        r'^sequenceSearch/$',
        views.ajaxsequencesearch,
        name='sequenceSearch'
    ),
    url(
        r'^jobDetail/(?P<job_id>\d+)/sequenceDetail/(?P<sequence_id>\d+)/$',
        views.sequenceDetailView,
        name='sequenceDetail'
    ),
    url(
        r'^renderSearch/$',
        views.ajaxrendersearch,
        name='renderSearch'
    ),
]

woodshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from lumberyard import views as lyviews

urlpatterns = [
    url(r'^$', lyviews.LoginView.as_view(), name='login'),
    url(r'^lumberyard/', include('lumberyard.urls', namespace='lumberyard')),
    url(r'^admin/', admin.site.urls),
]

lumberyard/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Fieldset, ButtonHolder
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)


class LoginForm(AuthenticationForm):
    
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            'username',
            'password',
            ButtonHolder(
                Submit('login','login', css_class='btn-primary')
            )
        )

class JobDetailForm(forms.Form):
    job_active = forms.BooleanField(label='Job Active')
    job_num = forms.CharField(label='Job Number',max_length=10)
    job_name = forms.CharField(label='Job Name',max_length=100)
    job_dir = forms.CharField(label='Job Folder',max_length=200)
    date_pitch = forms.DateField(label='Date Pitched')
    date_awarded = forms.DateField(label='Date Awarded',required=False)
    date_delivery = forms.DateField(label='Date of Delivery')
    email_alias = forms.EmailField(label='Email Alias')
    producer = forms.ChoiceField(label='Producer')
    agency = forms.CharField(label='Agency',required=False,max_length=200)
    agency_prod = forms.CharField(label='Agency Producer',required=False,max_length=200)
    agency_prod_email = forms.CharField(label='Agency Email',required=False,max_length=200)
    agency_prod_phone = forms.CharField(label='Agency Phone',required=False,max_length=50)
    client = forms.CharField(label='Client',required=False,max_length=200)
    client_contact_name = forms.CharField(label='Client Contact',required=False,max_length=200)
    client_contact_email = forms.CharField(label='Client Email',required=False,max_length=200)
    client_contact_phone = forms.CharField(label='Client Phone',required=False,max_length=50)
    lead_2D = forms.ChoiceField(label='Lead 2D')
    lead_3D = forms.ChoiceField(label='Lead 3D')
    milestones = forms.CharField(label='Milestones',required=False, max_length=200)
    delivery_specs = forms.ChoiceField(label='Delivery Specs')
    artist_list = forms.MultipleChoiceField(label='Artist List')
    
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.layout = Layout(
            Field('job_active', css_class='input-sm'),
        Field('job_num', css_class='input-sm'),
        Field('job_name', css_class='input-sm'),
        Field('job_dir', css_class='input-sm'),
        Field('date_pitch', css_class='input-sm'),
        Field('date_awarded', css_class='input-sm'),
        Field('date_delivery', css_class='input-sm'),
        Field('email_alias', css_class='input-sm'),
        Field('producer', css_class='input-sm'),
        Field('agency', css_class='input-sm'),
        Field('agency_prod', css_class='input-sm'),
        Field('agency_prod_email', css_class='input-sm'),
        Field('agency_prod_phone', css_class='input-sm'),
        Field('client', css_class='input-sm'),
        Field('client_contact_name', css_class='input-sm'),
        Field('client_contact_email', css_class='input-sm'),
        Field('client_contact_phone', css_class='input-sm'),
        Field('lead_2D', css_class='input-sm'),
        Field('lead_3D', css_class='input-sm'),
        Field('milestones', css_class='input-sm'),
        Field('delivery_specs', css_class='input-sm'),
        Field('artist_list', css_class='input-sm'),
        FormActions(Submit('save', 'save', css_class='btn-primary'))
    )

lumberyard/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django.views.generic import FormView
from lumberyard.forms import LoginForm, JobDetailForm
from lumberyard.models import Jobs, Sequence, Renders
from lumberyard.tables import JobsTable, SequenceTable, RendersTable
from django_tables2 import RequestConfig
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.db.models import Q
import time

@login_required(login_url='/')
def indexView(request):
    results = Jobs.objects.filter(Q(job_active = 1))
    table = JobsTable(results)
    RequestConfig(request, paginate={'per_page': 12}).configure(table)
    return render(request, 'lumberyard/index.html', {'table': table})


class LoginView(generic.FormView):
    form_class = LoginForm
    success_url = reverse_lazy('lumberyard:index')
    template_name = 'lumberyard/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)

def JobDetailView(request, job_id):
    job_name = Jobs.objects.get( id = job_id ).job_name
    job_num = Jobs.objects.get( id = job_id ).job_num
    producer = Jobs.objects.get( id = job_id ).producer
    email_alias = Jobs.objects.get( id= job_id ).email_alias
    lead_2D = Jobs.objects.get( id= job_id ).lead_2D
    lead_3D = Jobs.objects.get( id= job_id ).lead_3D
    date_awarded = Jobs.objects.get( id= job_id ).date_awarded
    date_pitch = Jobs.objects.get( id= job_id ).date_pitch
    date_delivery = Jobs.objects.get( id= job_id ).date_delivery
    agency = Jobs.objects.get( id= job_id ).agency
    agency_prod = Jobs.objects.get( id= job_id ).agency_prod
    agency_prod_email = Jobs.objects.get( id= job_id ).agency_prod_email
    agency_prod_phone = Jobs.objects.get( id= job_id ).agency_prod_phone
    client = Jobs.objects.get( id= job_id ).client
    client_contact_name = Jobs.objects.get( id= job_id ).client_contact_name
    client_contact_email = Jobs.objects.get( id= job_id ).client_contact_email
    client_contact_phone = Jobs.objects.get( id= job_id ).client_contact_phone
    results = Sequence.objects.filter(Q(job__job_name = job_name))
    table = SequenceTable(results)
    RequestConfig(request, paginate={'per_page': 12}).configure(table)
    return render(request, 'lumberyard/jobDetail.html', {
        'job_name': job_name,
        'job_num': job_num,
        'producer': producer,
        'email_alias': email_alias,
        'lead_2D': lead_2D,
        'lead_3D': lead_3D,
        'date_awarded': date_awarded,
        'date_pitch': date_pitch,
        'date_delivery': date_delivery,
        'agency': agency,
        'agency_prod': agency_prod,
        'agency_prod_email': agency_prod_email,
        'agency_prod_phone': agency_prod_phone,
        'client': client,
        'client_contact_name': client_contact_name,
        'client_contact_email': client_contact_email,
        'client_contact_phone': client_contact_phone,
        'table': table,
    })

def sequenceDetailView(request, job_id, sequence_id):
    job_name = Jobs.objects.get( id = job_id ).job_name
    job_num = Jobs.objects.get( id = job_id ).job_num
    sequence_name = Sequence.objects.get( id = sequence_id ).sequence_name
    artist_list = Jobs.objects.get( id = job_id ).artist_list.all()
    tasks = Sequence.objects.get ( id = sequence_id ).tasks.all()
    producer = Jobs.objects.get( id = job_id ).producer
    email_alias = Jobs.objects.get( id= job_id ).email_alias
    lead_2D = Jobs.objects.get( id= job_id ).lead_2D
    lead_3D = Jobs.objects.get( id= job_id ).lead_3D
    date_awarded = Jobs.objects.get( id= job_id ).date_awarded
    date_pitch = Jobs.objects.get( id= job_id ).date_pitch
    date_delivery = Jobs.objects.get( id= job_id ).date_delivery
    results = Renders.objects.filter(
        Q(shot_name__id = sequence_id ) &
        Q(shot_name__job_id = job_id)
    )
    table = RendersTable(results)
    RequestConfig(request, paginate={'per_page': 12}).configure(table)
    return render(request, 'lumberyard/sequenceDetail.html', {
        'job_id': job_id,
        'job_name': job_name,
        'job_num': job_num,
        'sequence_name': sequence_name,
        'artist_list': artist_list,
        'tasks': tasks,
        'producer': producer,
        'email_alias': email_alias,
        'lead_2D': lead_2D,
        'lead_3D': lead_3D,
        'date_awarded': date_awarded,
        'date_pitch': date_pitch,
        'date_delivery': date_delivery,
        'table': table,
    })

def ajaxjobsearch(request):

    if request.is_ajax():
        startdate = request.GET.get('startdate')
        enddate = request.GET.get('enddate')
        datetype = request.GET.get('datetype')
        jobstatus = request.GET.get('jobstatus')
        searchtext = request.GET.get('searchtext')
        if jobstatus != '2':
            if datetype == "date_awarded":
                if startdate != '' and enddate != '':
                    results = Jobs.objects.filter(
                        Q( job_active = jobstatus ) &
                        Q( date_awarded__range = [startdate, enddate] ) &
                        (Q( job_name__contains = searchtext ) |
                        Q( job_num__contains = searchtext ) |
                        Q( email_alias__contains = searchtext ) |
                        Q( producer__user__first_name__contains = searchtext ) |
                        Q( producer__user__last_name__contains = searchtext ) |
                        Q( lead_2D__user__first_name__contains = searchtext ) |
                        Q( lead_2D__user__last_name__contains = searchtext ) |
                        Q( lead_3D__user__first_name__contains = searchtext ) |
                        Q( lead_3D__user__last_name__contains = searchtext ) |
                        Q( agency__contains = searchtext ) |
                        Q( agency_prod__contains = searchtext ) |
                        Q( delivery_specs__spec_name__contains = searchtext ) |
                        Q( client__contains = searchtext ))
                    ).order_by( 'job_name' )
                    table = JobsTable(results)
                    RequestConfig(request, paginate={'per_page': 12}).configure(table)
                    return render(request, 'lumberyard/jobsTable.html', {'table': table})
                else:
                    results = Jobs.objects.filter(
                        Q( job_active = jobstatus ) &
                        (Q( job_name__contains = searchtext ) |
                        Q( job_num__contains = searchtext ) |
                        Q( email_alias__contains = searchtext ) |
                        Q( producer__user__first_name__contains = searchtext ) |
                        Q( producer__user__last_name__contains = searchtext ) |
                        Q( lead_2D__user__first_name__contains = searchtext ) |
                        Q( lead_2D__user__last_name__contains = searchtext ) |
                        Q( lead_3D__user__first_name__contains = searchtext ) |
                        Q( lead_3D__user__last_name__contains = searchtext ) |
                        Q( agency__contains = searchtext ) |
                        Q( agency_prod__contains = searchtext ) |
                        Q( delivery_specs__spec_name__contains = searchtext ) |
                        Q( client__contains = searchtext ))
                    ).order_by( 'job_name' )
                    table = JobsTable(results)
                    RequestConfig(request, paginate={'per_page': 12}).configure(table)
                    return render(request, 'lumberyard/jobsTable.html', {'table': table})

            else:
                if startdate != '' and enddate != '':
                    results = Jobs.objects.filter(
                        Q( job_active = jobstatus ) &
                        Q( date_delivery__range = [startdate, enddate] ) &
                        (Q( job_name__contains = searchtext ) |
                        Q( job_num__contains = searchtext ) |
                        Q( email_alias__contains = searchtext ) |
                        Q( producer__user__first_name__contains = searchtext ) |
                        Q( producer__user__last_name__contains = searchtext ) |
                        Q( lead_2D__user__first_name__contains = searchtext ) |
                        Q( lead_2D__user__last_name__contains = searchtext ) |
                        Q( lead_3D__user__first_name__contains = searchtext ) |
                        Q( lead_3D__user__last_name__contains = searchtext ) |
                        Q( agency__contains = searchtext ) |
                        Q( agency_prod__contains = searchtext ) |
                        Q( delivery_specs__spec_name__contains = searchtext ) |
                        Q( client__contains = searchtext ))
                    ).order_by( 'job_name' )
                    table = JobsTable(results)
                    RequestConfig(request, paginate={'per_page': 12}).configure(table)
                    return render(request, 'lumberyard/jobsTable.html', {'table': table})
                else:
                    results = Jobs.objects.filter(
                        Q( job_active = jobstatus ) &
                        (Q( job_name__contains = searchtext ) |
                        Q( job_num__contains = searchtext ) |
                        Q( email_alias__contains = searchtext ) |

lumberyard/templates/lumberyard/index.html
{% extends "lumberyard/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load group_filter %}
{% block title %}Jobs - Lumberyard{% endblock %}
{% block extrahead %}
    <link href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" rel="stylesheet" />
    <link href="{% static "lumberyard/css/jobstable.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script type="text/javascript">
      $( function() {
        $( '#datepicker1' ).datepicker();
        $( '#datepicker2' ).datepicker();
      } );
      $( document ).ready( function() {
        $( '#spinner' ).hide();
        $( '#searchbutton' ).click( function() {
            if ($( '#datepicker1' ).val()!=''&&$( '#datepicker2' ).val()=='') alert('Please insert the end date.');
            else if ($( '#datepicker1' ).val()==''&&$( '#datepicker2' ).val()!='') alert('Please insert the start date.');
            else if ($( '#datepicker1' ).val() > $( '#datepicker2' ).val()) alert('Start date must be before End date');
            else {
                startdate='';
                enddate='';
                if($( '#datepicker1' ).val()!=''&&$( '#datepicker2' ).val()!='') {
                    startdate = $('#datepicker1').val().substring(6, 10) + '-' + $('#datepicker1').val().substring(0, 2) + '-' + $('#datepicker1').val().substring(3, 5);
                    enddate = $('#datepicker2').val().substring(6, 10) + '-' + $('#datepicker2').val().substring(0, 2) + '-' + $('#datepicker2').val().substring(3, 5);
                }
                datetype = $( '#datetype' ).val();
                jobstatus = $( '#jobstatus' ).val();
                searchtext = $( '#searchtext').val();
                $( '.tabledata' ).html( '' ).load( '{% url 'lumberyard:jobSearch' %}?startdate=' + startdate + '&enddate=' + enddate + '&datetype=' + datetype + '&jobstatus=' + jobstatus + '&searchtext=' + searchtext );
            }
        });
      });

      $( document ).ajaxStart( function() {
        $( '#spinner' ).show();
        }).ajaxStop( function() {
        $( '#spinner' ).hide();
      });
    </script>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="top-navigation">
      <div id="logo-container"></div>
      <div id="nav-link">
        {% if request.user|has_group:"admin" %}
        <a href="{% url 'admin:index' %}" class="link">Admin</a><span style="color: #fdcf17;">|</span>
        {% endif %}
        <a href="{% url 'lumberyard:logout' %}" class="link">Logout</a>
      </div>
    </div>
    <hr>
  </div>
  <div class="row">
    <div class="searchfield">
      <form>
          <div id="jobtable">Job Table</div>
          <div id="datefield">
              Date Range:
              <input type="text" id="datepicker1">
              <span style="text-transform: lowercase;">to</span>
              <input type="text" id="datepicker2">
              <select id="datetype">
                   <option value="date_awarded">date_awarded</option>
                   <option value="date_delivery">date_delivery</option>
               </select>
          </div>
          <div id="jobstatusfield">
              <select id="jobstatus">
                   <option value="1">active</option>
                   <option value="0">inactive</option>
                   <option value="2">all</option>
              </select>
          </div>
          <div id="searchtextfield">
              <input type="text" id="searchtext">
          </div>
          <div id="searchbutton">
              <input type="reset" value="RESET" id="reset">
              <input type="button" value="SEARCH" id="searchbutton">
              <span id="spinner"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
          </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="tabledata">
        {% render_table table %}
    </div>
  </div>
{% endblock %}

lumberyard/templates/lumberyard/jobDetail.html
{% extends "lumberyard/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load group_filter %}
{% block title %}JobDetail - Lumberyard{% endblock %}
{% block extrahead %}
    <link href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" rel="stylesheet" />
    <link href="{% static "lumberyard/css/jobdetail.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script type="text/javascript">
      $( document ).ready( function() {
        $( '#spinner' ).hide();
        $( '#searchbutton' ).click( function() {
            if ($( '#sequencenum1' ).val()!=''&&$( '#sequencenum2' ).val()=='') alert('Please insert the end num.');
            else if ($( '#sequencenum1' ).val()==''&&$( '#sequencenum2' ).val()!='') alert('Please insert the start num.');
            else if (parseInt($( '#sequencenum1' ).val()) > parseInt($( '#sequencenum2' ).val())) alert('Start num must must be smaller than End num');
            else {
                sequencenum1='';
                sequencenum2='';
                if($( '#sequencenum1' ).val()!=''&&$( '#sequencenum2' ).val()!='') {
                    sequencenum1 = $('#sequencenum1').val();
                    sequencenum2 = $('#sequencenum2').val();
                }
                searchtext = $( '#searchtext').val();
                jobname = $( '#jobname' ).val();
                $( '.tabledata' ).html( '' ).load( '{% url 'lumberyard:sequenceSearch' %}?sequencenum1=' + sequencenum1 + '&sequencenum2=' + sequencenum2 + '&searchtext=' + searchtext +'&jobname=' + jobname);
            }
        });
      });

      $( document ).ajaxStart( function() {
        $( '#spinner' ).show();
        }).ajaxStop( function() {
        $( '#spinner' ).hide();
      });
    </script>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="top-navigation">
      <div id="logo-container"></div>
      <div id="nav-link">
        {% if request.user|has_group:"admin" %}
        <a href="{% url 'admin:index' %}" class="link">Admin</a><span style="color: #fdcf17;">|</span>
        {% endif %}
        <a href="{% url 'lumberyard:logout' %}" class="link">Logout</a>
      </div>
      <div id="job-info">
          {{ job_name }} - {{ job_num }}
          <input type="hidden" id="jobname" value="{{ job_name }}"/>
      </div>
    </div>
    <hr>
  </div>
  <div class="row">
    <div class="jobdetailinfo">
        <div id="jobdetaillabel" class="row">
            Job Detail
            <a href="{% url 'lumberyard:index' %}"><-- back to job list</a>
        </div>
        <div id="internal">
            <p id="internallabel">internal</p>
            <div id="internalcontent">
                <p>producer: {{ producer }}</p>
                <p>email alias: {{ email_alias }}</p>
                <p>2D lead: {{ lead_2D }}</p>
                <p>3D lead: {{ lead_3D }}</p>
                <p>date awarded: {{ date_awarded|date:"SHORT_DATE_FORMAT" }}</p>
                <p>pitched: {{ date_pitch|date:"SHORT_DATE_FORMAT" }}</p>
                <p>delivery: {{ date_delivery|date:"SHORT_DATE_FORMAT" }}</p>
            </div>
        </div>
        {% if request.user|has_group:"admin" or request.user|has_group:"producer" %}
        <div id="agency">
            <p id="agencylabel">agency</p>
            <div id="agencycontent">
                <p>agency: {{ agency }}</p>
                <p>agency contact: {{ agency_prod }}</p>
                <p>email: {{ agency_prod_email }}</p>
                <p>phone: {{ agency_prod_phone }}</p>
                <p class="blankline">blank line: same color as background </p>
                <p class="blankline">blank line: same color as background </p>
                <p class="blankline">blank line: same color as background </p>
            </div>
        </div>
        <div id="client">
            <p id="clientlabel">client</p>
            <div id="clientcontent">
                <p>client: {{ client }}</p>
                <p>client contact: {{ client_contact_name }}</p>
                <p>email: {{ client_contact_email }}</p>
                <p>phone: {{ client_contact_phone }}</p>
                <p class="blankline">blank line: same color as background </p>
                <p class="blankline">blank line: same color as background </p>
                <p class="blankline">blank line: same color as background </p>
            </div>
        </div>
        {% endif %}
    </div>
  </div>
  <div class="row">
    <div class="sequencesearchfield">
      <form>
          <div id="sequencetablelabel">SEQUENCE LIST</div>
          <div id="datefield">
              SHOT # RANGE:
              <input type="text" id="sequencenum1">
              <span style="text-transform: lowercase;">to</span>
              <input type="text" id="sequencenum2">
          </div>
          <div id="searchtextfield">
              <input type="text" id="searchtext">
          </div>
          <div id="searchbutton">
              <input type="reset" value="RESET" id="reset">
              <input type="button" value="SEARCH" id="searchbutton">
              <span id="spinner"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
          </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="tabledata">
        {% render_table table %}
    </div>
  </div>
{% endblock %}

lumberyard/templates/lumberyard/sequenceDetail.html
{% extends "lumberyard/base.html" %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% load group_filter %}
{% block title %}SequenceDetail - Lumberyard{% endblock %}
{% block extrahead %}
    <link href="{% static "django_tables2/themes/paleblue/css/screen.css" %}" rel="stylesheet" />
    <link href="{% static "lumberyard/css/sequencedetail.css" %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"></script>
    <script type="text/javascript">
      $( document ).ready( function() {
        $( '#spinner' ).hide();
            $( '#searchbutton' ).click( function() {
            searchtext = $( '#searchtext').val();
            jobname = $( '#jobname' ).val();
            sequencename = $( '#sequencename' ).val();
            $( '.tabledata' ).html( '' ).load( '{% url 'lumberyard:renderSearch' %}?searchtext=' + searchtext +'&jobname=' + jobname + '&sequencename=' + sequencename);
        });
      });

      $( document ).ajaxStart( function() {
        $( '#spinner' ).show();
        }).ajaxStop( function() {
        $( '#spinner' ).hide();
      });
    </script>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="top-navigation">
      <div id="logo-container"></div>
      <div id="nav-link">
        {% if request.user|has_group:"admin" %}
        <a href="{% url 'admin:index' %}" class="link">Admin</a><span style="color: #fdcf17;">|</span>
        {% endif %}
        <a href="{% url 'lumberyard:logout' %}" class="link">Logout</a>
      </div>
      <div id="sequence-info">
          {{ job_name }} - {{ job_num }} | {{ sequence_name }}
          <input type="hidden" id="jobname" value="{{ job_name }}"/>
          <input type="hidden" id="sequencename" value="{{ sequence_name }}"/>
      </div>
    </div>
    <hr>
  </div>
  <div class="row">
    <div class="sequencedetailinfo">
        <div id="sequencedetaillabel" class="row">
            Sequence Detail
            <a href="/lumberyard/jobDetail/{{ job_id }}"><-- back to sequence list</a>
        </div>
        <div id="internal">
            <p id="internallabel">internal</p>
            <div id="internalcontent">
                <p>producer: {{ producer }}</p>
                <p>email alias: {{ email_alias }}</p>
                <p>2D lead: {{ lead_2D }}</p>
                <p>3D lead: {{ lead_3D }}</p>
                <p>date awarded: {{ date_awarded|date:"SHORT_DATE_FORMAT" }}</p>
                <p>pitched: {{ date_pitch|date:"SHORT_DATE_FORMAT" }}</p>
                <p>delivery: {{ date_delivery|date:"SHORT_DATE_FORMAT" }}</p>
            </div>
        </div>
        <div id="artists">
            <p id="artistslabel">artists</p>
            <hr>
            <div id="artistscontent">
                {% for artist in artist_list|slice:"7" %}
                {% if artist %}
                <p>&nbsp;&nbsp;&nbsp;{{ artist }}</p>
                <hr>
                {% else %}
                <p class="blankline">&nbsp;&nbsp;&nbsp;blank line: same color as background </p>
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div id="tasks">
            <p id="taskslabel">tasks</p>
            <hr>
            <div id="taskscontent">
                {% for task in tasks|slice:"7"%}
                <p>&nbsp;&nbsp;&nbsp;{{ task }}</p>
                <hr>
                {% endfor %}
            </div>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="rendersearchfield">
      <form>
          <div id="rendertablelabel">Render List</div>
          <div id="searchdiv">
              <input type="button" value="SEARCH" id="searchbutton">
              <span id="spinner"><img src="http://upload.wikimedia.org/wikipedia/commons/d/de/Ajax-loader.gif"/></span>
              <input type="reset" value="RESET" id="reset">
          </div>
          <div id="searchtextfield">
              <input type="text" id="searchtext">
          </div>
      </form>
    </div>
  </div>
  <div class="row">
    <div class="tabledata">
        {% render_table table %}
    </div>
  </div>
{% endblock %}